"""Initial migration

Revision ID: e33da1630f80
Revises: 
Create Date: 2023-10-12 02:46:47.058507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e33da1630f80"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("location_id", sa.String(length=36), nullable=False),
        sa.Column("api_key", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("client_id", "location_id"),
    )
    op.create_table(
        "accounting",
        sa.Column("accounting_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("location_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("ort_session_time", sa.Float(), nullable=True),
        sa.Column("matting_time", sa.Float(), nullable=True),
        sa.Column("main_operation_time", sa.Float(), nullable=True),
        sa.Column("image_download_time", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["client.client_id"], use_alter=True),
        sa.ForeignKeyConstraint(
            ["location_id"], ["client.location_id"], use_alter=True
        ),
        sa.PrimaryKeyConstraint("accounting_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounting")
    op.drop_table("client")
    # ### end Alembic commands ###
